### ISSUE TITLE
Allow injecting IPFS instance

### ISSUE THREAD

**Issue by haadcode** [ConsenSys/uport-persona#17]
It would be great to be able to inject the IPFS api instead of uport-persona providing/handling the IPFS instance.

There are a few reasons for this:
- the ipfs api used in uport is a very old one and the API has changed (and will do so in the future)
- can't assume uport, and as such the ipfs instance, is always used from the browser
  - this becomes a problem when uport is used in Electron: I want to run my IPFS instance in Electron's main process while uPort should run in the renderer process (due to CORS, and performance)
- doesn't support js-ipfs (IPFS's JS implementation) atm. 
  - while it's still early for js-ipfs, it's working. Orbit and all its related modules runs tests with both implementations: js-ipfs-api (Go) and js-ipfs (JS)

So, essentially, I would like to be able to do the same as now with

```
persona.setProvides(ipfsProvider, uportProvider)
```

with the difference that **it should respect the ipfsProvider I pass it to**. Atm, the ipfs-js gets replaced with browser-ipfs which doesn't respect it (but rather does its own requests).

For the browser (using js-ipfs), it would look like:

``` javascript
const IPFS = require('ipfs')
...
persona.setProviders(new IPFS(), uportProvider)
```

And for Node.js (using go-ipfs), it would look like:

``` javascript
const IPFS = require('ipfs-api')
...
persona.setProviders(new IPFS(), uportProvider)
```

**Comment by pelle** [comment]
@haadcode this is now supported. You can instantiate the Registry with an `ipfs` option which could be any ipfs-api compliant object.
