### ISSUE TITLE
Can't install npm package

### ISSUE THREAD

**Issue by haadcode** [ConsenSys/uport-persona#20]
I added `uport-persona` to my application with `npm install uport-persona --save`. It fails to install the package with the following error:
```
> uport-persona@1.2.4 install /Users/samuli/code/orbit/node_modules/uport-persona
> npm run build


> uport-persona@1.2.4 prebuild /Users/samuli/code/orbit/node_modules/uport-persona
> node_modules/standard/bin/cmd.js

sh: node_modules/standard/bin/cmd.js: No such file or directory

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! uport-persona@1.2.4 prebuild: `node_modules/standard/bin/cmd.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the uport-persona@1.2.4 prebuild script 'node_modules/standard/bin/cmd.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
...
```

I would suggest to not run the build step at install but to include the `dist/` in the npm package.

@jeffscottward @oed This is pretty urgent as Devcon2 starts on Monday and we want to demo uPort. For that, we need to record videos tomorrow. Sorry to rush you, but if you can take a look and let me know what I can do to resolve this. I'll play around and see what I can do in the meanwhile and keep you updated.

**Comment by haadcode** [comment]
Cloning and running `npm i && npm run build` works fine, so I suspect this is something to do with paths...

**Comment by jeffscottward** [comment]
Sorry about that haadcode. Our intern was supposed to work on this this, it's an order of operations thing regarding StandardJS linting. Install that first on it own and then try again. May need to edit the existing install script in package json, I think that's supposed to be post-install not install

**Comment by jeffscottward** [comment]
Will commit when I get the chance

**Comment by oed** [comment]
Version 1.2.5 is out, which includes dist folder.
