### ISSUE TITLE
How do I get 'myAddress'?

### ISSUE THREAD

**Issue by haadcode** [ConsenSys/uport-persona#21]
The API has changed somewhat in the past two weeks and it looks like you're not using this anymore:
```
web3.eth.getCoinbase((err, myAddress) => { ... }
```

Rather, it looks like I need to know my address beforehand. How do I get the address of my profile without knowing it?

ping @jeffscottward @oed

**Comment by oed** [comment]
```
web3.eth.getCoinbase((err, myAddress) => { ... })
```
Should still work fine. What happens when you do that?

**Comment by oed** [comment]
Wait, this is an error you are getting with uport-lib right?

**Comment by haadcode** [comment]
@oed looking into it right now. If I use the function ^ I get: `Error: etherbase address must be explicitly specified`, same if I try to call it with `web3.eth.coinbase` (getter).

**Comment by oed** [comment]
@haadcode could you please provide steps to reproduce?

**Comment by haadcode** [comment]
This is the code I run:
```javascript
    // console.log("Waiting for uPort authorization...")
    const web3 = new Web3()
    // const uport = new Uport("Orbit")
    let web3Prov = new web3.providers.HttpProvider('https://consensysnet.infura.io:8545')
    // const uportProvider = uport.getUportProvider()
    web3.setProvider(web3Prov)

    // ...

    web3.eth.getCoinbase((err, res) => {
        if (err) reject(err)

        persona = new MutablePersona(res, ipfs, web3Prov)
        // ...
    })
```

Using `web3@0.17.0-beta`

**Comment by haadcode** [comment]
And, in that code, `err` after calling `getCoinbase` is the one mentioned above.

**Comment by haadcode** [comment]
It errors here:
```javascript
HttpProvider.prototype.sendAsync = function (payload, callback) {
    var request = this.prepareRequest(true); 

    request.onreadystatechange = function() {
        if (request.readyState === 4) {
            var result = request.responseText;
            var error = null;

            try {
                result = JSON.parse(result);
            } catch(e) {
                error = errors.InvalidResponse(request.responseText);                
            }

            callback(error, result); // ERROR
        }
    };
    
    try {
        request.send(JSON.stringify(payload));
    } catch(error) {
        callback(errors.InvalidConnection(this.host));
    }
};
```

**Comment by oed** [comment]
Right, you need to use the web3 provider given by uport-lib. Looks like it's commented out in your code.

**Comment by oed** [comment]
```
 // console.log("Waiting for uPort authorization...")
    const web3 = new Web3()
    const uport = new Uport("Orbit")
    const uportProvider = uport.getUportProvider('https://consensysnet.infura.io:8545')
    web3.setProvider(uportProvider)

    // ...

    web3.eth.getCoinbase((err, res) => {
        if (err) reject(err)

        persona = new MutablePersona(res, ipfs, web3Prov)
        // ...
    })
```
This should work

**Comment by haadcode** [comment]
@oed So I need to include also the `uport-lib` module?

**Comment by haadcode** [comment]
On that note, `uport-lib` is still private, I can't release the Orbit version if it depends on a private repo :/

**Comment by haadcode** [comment]
Ah, but the package is on npm. Got it, disregard the previous comment!

**Comment by oed** [comment]
Yes, the uport persona module is only for interacting with persona information, while uport-lib is for using the web3 object, logging in and signing transactions on the phone.
Err, I thought @jeffscottward had released it. One sec.

**Comment by christianlundkvist** [comment]
@haadcode - uport-lib is public now as well, sorry for the troubles, lots of moving parts for DEVcon!

**Comment by christianlundkvist** [comment]
Thanks @oed for being on top of it! 👍

**Comment by haadcode** [comment]
Ok, got a bit further. Seems to be working uPort-wise. Thank you so much @oed for helping out!

Next problem: the great firewall (or maybe not). This call never returns:
```javascript
uport.getUserPersona().then(function (persona) {
...
})
```

I assume that calls ipfs.cat/get for the profile info. It might be that my IPF daemon can't connect, might be something else. I've tried with no VPN and with a VPN in various locations. IPFS works fine over VPN (I've confirmed this), so not sure why it can't connect to yours.

Can you pass me your nodes' ids via email haad@ipfs.io? I would like to try and see if I can connect to them.

**Comment by haadcode** [comment]
Oh, have you reset the profiles recently? Maybe my profile's hash doesn't exist anymore and the requests in ipfs timeout after a really really long time...

**Comment by christianlundkvist** [comment]
@haadcode Not sure if that's the issue, can you try going to testapp.uport.me and see if you can connect and if you see any of your profile data?

**Comment by christianlundkvist** [comment]
Also see if you are able to run the file examples/example.html in uport-lib.

**Comment by haadcode** [comment]
@christianlundkvist ok, got it working now! I need to set ehe `ipfsProvider` to `ipfs.infura.io`. That doesn't make sense. Why does the program need to connect to a specific IPFS host?

**Comment by haadcode** [comment]
And the next problem: `Error: The private key used must match the one set in the persona.` when I call persona.addAttribute(). I've probably replaced the private key with a new one, or perhaps the testapp or example created a private key, so the error makes sense, but how does this work now? Who sets the private key and if it's uPort, how can I get that so sign the attributes?

**Comment by oed** [comment]
@haadcode yeah, I've been having that problem too. It should work with your own ipfs node, but I think there is something wrong with infura and propagation on the ipfs network.

**Comment by haadcode** [comment]
I think I figured it out. Need to call the `setPublicSigningKey(privKey)` first.

**Comment by oed** [comment]
@haadcode So right now the private key that can be used for doing `persona.addAttribute()` resides on the uport-mobile app. So this behaviour is intended since we want the added attribute to be self signed by that key. In the future we plan on implementing a function that sends a new attribute to the phone for signing and adding. 
What you can do instead is to use `persona.signAttribute()` to sign an attribute with a third party private key.

**Comment by haadcode** [comment]
Yes! That does it. All good for now. Will let you know if any more obstacles occur. Thank you so much for helping @christianlundkvist @oed @jeffscottward.

**Comment by oed** [comment]
You should **not** be calling `setPublicSigningKey(privKey)` since that will change the public key for the entire persona. 
There should probably be a check that you have to have the old privKey to change to a new one.

**Comment by haadcode** [comment]
@oed Oh... So hmmm, I still don't quite understand which key is which. The `privKey` above should be *uPort's* private key? Not Orbit's private key that is used for Orbit's public signing key?

**Comment by haadcode** [comment]
The problem above aside, I can confirm that everything is working again! Hooray, we can demo :) \o/

<img width="658" alt="screen shot 2016-09-17 at 16 20 39" src="https://cloud.githubusercontent.com/assets/7499694/18607030/104bd74c-7cf3-11e6-948b-066170d6a1ce.png">

**Comment by haadcode** [comment]
@oed Oops I missed your earlier comment re. keys. Let me try the `signAttribute` and see that it works.

**Comment by oed** [comment]
@haadcode yes, that is correct. This library is used on uport-mobile and should also work if you just want to create a profile for your regular ethereum address. 
The way this could be done for now is as follows:
```js
let claim = persona.signAttribute({attrName: value}, orbitPrivKey, myAddress)
persona.addClaim(claim)
```
This is in a way misusing the function, but will have to do until we can send attributes to the phone for signing.

**Comment by oed** [comment]
The Infura team are aware of and are working on their connectivity issues btw.

**Comment by haadcode** [comment]
@oed what's the `thirdPartyAddress` I need to provide to the `signAttribute` function?

**Comment by oed** [comment]
@haadcode So the intended use of `signAttribute` is for third party identities to sign some information related to you. So the `thirdPartyAddress` would be their uport address. 
However in this case just using the address of your uport address is fine.

**Comment by haadcode** [comment]
YES!! All good and it works now. Pheeew. Again, thank you so much for helping @oed and everyone else!

Btw. I like the new API 👍

**Comment by oed** [comment]
Thanks for helping out testing! When will we be able to chat on orbit? :D

**Comment by haadcode** [comment]
Sorry @oed, came across problems :/ It seems the attribute I try to sign doesn't go through, ie. my uPort profile is missing `orbitKey` field when queried. 

Is it required to create that attribute before it can be signed? Can this be related to connectivity? I notice that while my uPort profile picture does change, I can't retrieve the hash (I can't get with a locally running ipfs daemon either, nor via the ipfs.io gateway).

**Comment by oed** [comment]
Did you change anything in the profile in uport-mobile after you added the new field? Might be related to how the profile is buffered in the mobile app. There should be no problem adding an attribute before it's signed using `addClaim`.

**Comment by haadcode** [comment]
@oead I made a brand new profile. So, should I call addClaim before signing the attribute?

**Comment by haadcode** [comment]
The code is now:
```javascript
        return uport.getUserPersona()
          .then((res) =>{
            persona = res
            uportProfile = persona.getProfile()
// ...
            persona.signAttribute({ orbitKey: pubKeyHash }, privKey, persona.address)
```

Those are the only methods I call.

**Comment by oed** [comment]
Aha, it should be 
```js 
return uport.getUserPersona()
          .then((res) =>{
            persona = res
            uportProfile = persona.getProfile()
// ...
            let orbitClaim = persona.signAttribute({ orbitKey: pubKeyHash }, privKey, persona.address)
            persona.addClaim(orbitClaim)
```

**Comment by haadcode** [comment]
Ok, will try this. I trust it'll work since my iPhone just died and I can't find the charger :D I'll report back as soon as I find one :)

**Comment by haadcode** [comment]
@oed if you feel adventurous, you can try to verify the fix: clone orbit (branch: pubsubport), login with uPort, say something on some channel, click your username and you should see "Signing Key" (or in the log a message "uPort Profile Data" that contains the data received from uPort).

**Comment by oed** [comment]
@haadcode The call to `addClaim` will trigger a tx (Show of QR-code) but that should be fine.

**Comment by haadcode** [comment]
@oed Found my charger and changed the code. Unfortunately it doesn't work :/ I don't get a QR scan screen and the attribute is still missing from the profile. Tried with an old profile and with a fresh one.

Any suggestions?

**Comment by oed** [comment]
Sorry, I'm being stupid. With the new version you have to call `persona.writeToRegistry()` in order to make the changes permanent. The code in your case would be:
```js
let orbitClaim = persona.signAttribute({ orbitKey: pubKeyHash }, privKey, persona.persona.addClaim(orbitClaim)
persona.writeToRegistry()
```
The reason it's done this way is because we don't want to put updates on the blockchain multiple times if you're adding multiple attributes.

**Comment by haadcode** [comment]
@oed ok, now I get the QR screen. how long does it take for the attribute to appear in he profile? Should it be instant?

**Comment by oed** [comment]
It takes as long as it takes to mine the block. The promise should return an ethereum txHash. This can be used to check if a block has been mined using web3.

**Comment by haadcode** [comment]
Success! I can see the attribute now. Thank you @oed, you've been great help! ❤️ 

<img width="651" alt="screen shot 2016-09-17 at 23 49 04" src="https://cloud.githubusercontent.com/assets/7499694/18609309/89012096-7d31-11e6-9bd7-b4916b680259.png">

**Comment by christianlundkvist** [comment]
Awesome! Thanks so much @oed for helping out!
